{{- if and (not .Values.secretKey.existingSecret) .Values.secretKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-webui.fullname" . }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secretKey.existingSecretKey }}: {{ .Values.secretKey.value | b64enc | quote }}
{{- end }}
