all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site02:
      children:
        iw:
          children:
            archlinux:
              children:
                arch:
                  hosts:
                archarm:
                  hosts:
