all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site01:
      vars:
        pacman_mirror_server: 192.168.30.61
      children:
        tk_pv:
          children:
            archlinux:
              children:
                arch:
                  hosts:
                    tk_llm01:
                      ansible_host: 192.168.20.17
                    tk_worker01:
                      ansible_host: 192.168.20.18
                    tk_bastion01:
                      ansible_host: 192.168.20.60
                    tk_hermes01:
                      ansible_host: 192.168.20.36
                    tk_llm_proxy01:
                      ansible_host: 192.168.20.70
                    tk_memory01:
                      ansible_host: 192.168.20.71
                    tk_db01:
                      ansible_host: 192.168.20.52
                    tk_k8s_cp01:
                      ansible_host: 192.168.20.41
                    tk_k8s_wk01:
                      ansible_host: 192.168.20.81
                    tk_k8s_wk02:
                      ansible_host: 192.168.20.82
                    tk_k8s_wk03:
                      ansible_host: 192.168.20.83
                    tk_k8s_nfs01:
                      ansible_host: 192.168.20.51
        lxc:
          hosts:
            tk_worker01:
            tk_bastion01:
            tk_hermes01:
            tk_llm_proxy01:
            tk_memory01:
            tk_db01:

        worker:
          hosts:
            tk_worker01:
            tk_hermes01:

        hermes:
          hosts:
            tk_hermes01:

        bastion:
          hosts:
            tk_bastion01:

        llm:
          children:
            llm_backend:
              hosts:
                tk_llm01:
            llm_proxy:
              hosts:
                tk_llm_proxy01:

        memory:
          hosts:
            tk_memory01:

        database:
          hosts:
            tk_db01:

        kubernetes:
          children:
            kubernetes_control_plane:
              hosts:
                tk_k8s_cp01:
            kubernetes_worker:
              hosts:
                tk_k8s_wk01:
                tk_k8s_wk02:
                tk_k8s_wk03:

        kubernetes_nfs:
          hosts:
            tk_k8s_nfs01:
