all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site02:
      vars:
        pacman_cache_server: 192.168.64.61
      children:
        iw:
          children:
            archlinux:
              children:
                arch:
                  hosts:
                    iw_cache01:
                      ansible_host: 192.168.64.61
                archarm:
                  hosts:

        cache:
          hosts:
            iw_cache01:
