all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site01:
      children:
        tk:
          children:
            archlinux:
              children:
                arch:
                  hosts:
                    tk_bastion01:
                      ansible_host: 192.168.30.30
                    tk_dns01:
                      ansible_host: 192.168.30.3
                    tk_vm01:
                      ansible_host: 192.168.30.90
                    tk_vm02:
                      ansible_host: 192.168.30.91
                    tk_vm03:
                      ansible_host: 192.168.30.92
                archarm:
                  hosts:

        lxc:
          hosts:
            tk_bastion01:
            tk_dns01:

        vm:
          hosts:
            tk_vm01:
            tk_vm02:
            tk_vm03:

        bastion:
          hosts:
            tk_bastion01:

        docker:
          hosts:

        grafana:
          hosts:

        jenkins:
          hosts:

        dns:
          hosts:
            tk_dns01:

        proxmox:
          hosts:
            tk_proxmox01:
              ansible_host: 192.168.30.55
