all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site01:
      vars:
        pacman_mirror_server: 192.168.30.61
      children:
        tk:
          children:
            archlinux:
              children:
                arch:
                  hosts:
                    tk_bastion01:
                      ansible_host: 192.168.30.30
                    tk_dns01:
                      ansible_host: 192.168.30.3
                    tk_cache01:
                      ansible_host: 192.168.30.61
        lxc:
          hosts:
            tk_bastion01:
            tk_dns01:

        bastion:
          hosts:
            tk_bastion01:

        docker:
          hosts:

        dns:
          hosts:
            tk_dns01:

        cache:
          hosts:
            tk_cache01:

        proxmox:
          hosts:
            tk_proxmox01:
              ansible_host: 192.168.30.55
