all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site02:
      vars:
        pacman_cache_server: 192.168.32.61
        pacman_cache_peer_servers:
          - 192.168.30.61
      children:
        archlinux:
          children:
            arch:
              hosts:
                iw_dns01:
                  ansible_host: 192.168.32.100
                iw_bastion01:
                  ansible_host: 192.168.32.60
                iw_cache01:
                  ansible_host: 192.168.32.61
            archarm:
              hosts:

        lxc:
          hosts:
            iw_dns01:
            iw_bastion01:

        bastion:
          hosts:
            iw_bastion01:

        dns:
          hosts:
            iw_dns01:

        cache:
          hosts:
            iw_cache01:

        proxmox:
          hosts:
            iw_proxmox01:
              ansible_host: 192.168.32.50
