all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site02:
      vars:
        pacman_mirror_server: 192.168.32.61
      children:
        iw:
          children:
            archlinux:
              children:
                arch:
                  hosts:
