---
opencode_package_manifest:
  repository:
    - opencode
    - python
  aur: []

opencode_user: opencode

opencode_provider_id: llama.cpp
opencode_provider_name: llama-swap(tk)
opencode_provider_package: "@opencode/ai/providers/openai-compatible"
opencode_base_url: 'http://{{ local_llm_ip }}:12434/v1'
opencode_model_capabilities:
  tools: true
  input:
    - text
  output:
    - text
opencode_models:
  Qwen3.8-Flash-Next-Gufo-Q4-thinking:
    name: Qwen3.8-Flash-Next-Q4
    capabilities: '{{ opencode_model_capabilities }}'
  DeepSeek-V4-Flash-Gufo-IQ2XXS-DSpark:
    name: DeepSeek-V4-Flash-IQ2XXS-DSpark
    capabilities: '{{ opencode_model_capabilities }}'
    limit:
      context: 131072
      output: 8192
    compatibility:
      reasoningField: reasoning_content
opencode_default_model_name: DeepSeek-V4-Flash-Gufo-IQ2XXS-DSpark
opencode_default_model: '{{ opencode_provider_id }}/{{ opencode_default_model_name }}'
