---
- name: "archlinux-keyringを先に更新かける"
  become: true
  community.general.pacman:
    name: '{{ initialize_node_package_manifest.repository | select("equalto", "archlinux-keyring") | first }}'
    state: latest

- name: '必要なパッケージを追加する'
  become: true
  community.general.pacman:
    name: '{{ initialize_node_package_manifest.repository }}'
    state: present

- name: '日本語ロケールの生成'
  become: true
  community.general.locale_gen:
    name: ja_JP.UTF-8

- name: '日本語ロケールを使う'
  become: true
  ansible.builtin.copy:
    content: 'LANG=ja_JP.UTF-8'
    dest: /etc/locale.conf
    mode: '0644'

- name: 'rustのdefaultをstableに設定'
  ansible.builtin.command:
    cmd: 'rustup default stable'
  register: rustup_default
  changed_when: "'unchanged' not in (rustup_default.stdout + rustup_default.stderr)"

- name: 'グローバルなzshrcを置く'
  become: true
  ansible.builtin.copy:
    src: zshrc
    dest: /etc/zsh/zshrc
    mode: '0644'

- name: 'sudoグループを作成する'
  tags: node_credentials
  become: true
  ansible.builtin.group:
    name: sudo
    state: present

- name: 'sudoグループに所属しているユーザがパスワードなしでsudoできるようにする'
  tags: node_credentials
  become: true
  community.general.sudoers:
    name: sudo-maintainer
    group: sudo
    nopassword: true
    commands: ALL

- name: 'メンテナンス用のユーザを作成する'
  tags: node_credentials
  become: true
  ansible.builtin.user:
    name: maintainer
    shell: /usr/bin/zsh
    groups: sudo, wheel
    append: yes
    password: "{{ maintainer_password_hash }}"

- name: 'メンテナンス用のユーザのauthorized_keysを設定する'
  ansible.builtin.include_role:
    name: authorized-keys
    apply:
      tags:
        - authorized_keys
        - node_credentials
  tags:
    - authorized_keys
    - node_credentials

- name: 'rootのパスワードを変更する'
  tags: node_credentials
  become: true
  ansible.builtin.user:
    name: root
    password: "{{ root_password_hash }}"

- name: "systemd-resolvedと共存する設定"
  become: true
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true

- name: 'Grafana Alloyを追加する'
  kewlfft.aur.aur:
    name: '{{ initialize_node_package_manifest.aur }}'
    state: latest

- name: 'Alloyの設定を置く'
  tags: alloy_config
  become: true
  ansible.builtin.template:
    src: config.alloy.j2
    dest: /etc/alloy/config.alloy
    mode: '0644'
  diff: false
  vars:
    id: "homelab"
    cfg: "{{ alloy_homelab }}"
  notify: 'alloyを再起動する'

- name: 'alloyの設定を上書きする用のディレクトリを作成する'
  tags: alloy_config
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/alloy.service.d
    state: "directory"
    mode: '0755'

- name: '上書き用ユニットファイルを置く'
  tags: alloy_config
  become: true
  ansible.builtin.template:
    src: alloy-override.j2
    dest: /etc/systemd/system/alloy.service.d/override.conf
    mode: '0600'
  vars:
    cfg: "{{ alloy_homelab }}"
  notify: 'alloyを再起動する'
  diff: false

- name: 'alloy.serviceを有効化'
  tags: alloy_config
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: alloy
    daemon_reload: true
