---
- name: '必要なパッケージを追加する'
  become: true
  community.general.pacman:
    name: '{{ item.name }}'
    state: installed
  with_items: '{{ hermes_requirements_package }}'

- name: '必要なAURパッケージを追加する'
  kewlfft.aur.aur:
    name: '{{ item.name }}'
    state: present
  with_items: '{{ hermes_requirements_aur_package }}'

- name: 'hermes用のユーザを作成する'
  become: true
  ansible.builtin.user:
    name: hermes
    shell: /usr/bin/zsh
    password: "{{ vault_maintainer_password | password_hash('sha512') }}"

- name: 'hermesユーザにopencodeをセットアップする'
  ansible.builtin.include_role:
    name: opencode
  vars:
    opencode_user: hermes
