---
- name: 'hindsightグループを作成する'
  become: true
  ansible.builtin.group:
    name: hindsight
    state: present

- name: 'hindsight用のユーザを作成する'
  become: true
  ansible.builtin.user:
    name: hindsight
    shell: /usr/bin/zsh
    groups: hindsight,docker
    append: yes
    password_lock: true

- name: 'hindsight用ディレクトリの存在確認'
  become: true
  ansible.builtin.stat:
    path: /home/hindsight/.hindsight
  register: hindsight_dir

- name: 'hindsight用ディレクトリを掘る'
  become: true
  become_user: hindsight
  ansible.builtin.file:
    path: ~/.hindsight
    state: "directory"
    owner: hindsight
    mode: '0755'
  when: not hindsight_dir.stat.exists

- name: 'docker ディレクトリを掘る'
  become: true
  become_user: hindsight
  ansible.builtin.file:
    path: ~/docker
    state: directory
    owner: hindsight
    mode: '0755'

- name: 'compose.yamlを置く'
  become: true
  become_user: hindsight
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: ~/docker/compose.yaml
    mode: '0644'
  diff: false

- name: 'docker compose up -d'
  become: true
  become_user: hindsight
  community.docker.docker_compose_v2:
    project_src: ~/docker
    state: "present"
  register: hindsight_status

- name: "起動できたか確認する"
  ansible.builtin.debug:
    var: hindsight_status.failed
