---
- name: '必要なパッケージを追加する'
  become: true
  community.general.pacman:
    name: '{{ opencode_package_manifest.repository }}'
    state: installed

- name: 'config用ディレクトリを掘る'
  become: true
  ansible.builtin.file:
    path: '~{{ opencode_user }}/.config/opencode'
    state: "directory"
    owner: '{{ opencode_user }}'
    group: '{{ opencode_user }}'
    mode: "0755"

- name: 'AGENTS設定を置く'
  become: true
  ansible.builtin.copy:
    src: AGENTS.md
    dest: '~{{ opencode_user }}/.config/opencode/AGENTS.md'
    owner: '{{ opencode_user }}'
    group: '{{ opencode_user }}'
    mode: "0644"

- name: 'opencodeの設定ファイルを置く'
  become: true
  ansible.builtin.template:
    src: config.json.j2
    dest: '~{{ opencode_user }}/.config/opencode/config.json'
    owner: '{{ opencode_user }}'
    group: '{{ opencode_user }}'
    mode: "0644"
    validate: '/usr/bin/python -c "import json, sys; json.load(open(sys.argv[1]))" %s'
  diff: false
