nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: nginx
  tag: "1.31.6-alpine-slim"
  pullPolicy: IfNotPresent

backend:
  addresses: []
  port: 3000

proxy:
  clientMaxBodySize: 100m
  readTimeout: 3600s
  sendTimeout: 3600s

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

gateway:
  className: cilium
  hostname: ""
  network: private
  loadBalancerIP: ""
  annotations: {}
  tls:
    secretName: ""
    certificate:
      create: true
      issuerRef:
        name: homelab-ca
        kind: ClusterIssuer
        group: cert-manager.io
      duration: 2160h
      renewBefore: 720h
