---
- name: 'grafanaをインストール'
  kewlfft.aur.aur:
    name:
      - grafana-bin
    state: present

- name: 'grafana.serviceを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: grafana

- name: 'prometheusをインストール'
  become: true
  community.general.pacman:
    name: prometheus
    state: present
  notify: 'prometheusを再起動する'

- name: 'prometheusの設定を置く'
  become: true
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'
  notify: 'prometheusを再起動する'

- name: 'prometheusを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: prometheus
