---
- name: '必要なパッケージを追加する'
  become: true
  community.general.pacman:
    name: '{{ item.name }}'
    state: installed
  with_items: '{{ required_packages }}'

- name: 'searxngグループを作成する'
  become: true
  ansible.builtin.group:
    name: searxng
    state: present

- name: 'searxng用のユーザを作成する'
  become: true
  ansible.builtin.user:
    name: searxng
    shell: /usr/bin/zsh
    groups: searxng,docker
    append: yes
    password: "{{ vault_maintainer_password | password_hash('sha512') }}"

- name: 'docker.serviceを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: docker

- name: 'searxng用ディレクトリの存在確認'
  become: true
  ansible.builtin.stat:
    path: /home/searxng/.searxng
  register: searxng_dir

- name: 'searxng用ディレクトリを掘る'
  become: true
  become_user: searxng
  ansible.builtin.file:
    path: ~/.searxng
    state: "directory"
    recurse: true
    owner: searxng
    mode: '0755'
  when: not searxng_dir.stat.exists

- name: 'docker ディレクトリを掘る'
  become: true
  become_user: searxng
  ansible.builtin.file:
    path: ~/docker
    state: directory
    recurse: true
    owner: searxng
    mode: '0755'

- name: 'compose.yamlを置く'
  become: true
  become_user: searxng
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: ~/docker/compose.yaml

- name: 'docker compose up -d'
  become: true
  become_user: searxng
  community.docker.docker_compose_v2:
    project_src: ~/docker
    state: "present"
  register: searxng_status

- name: "起動できたか確認する"
  ansible.builtin.debug:
    var: searxng_status.failed

