---
kubernetes_control_plane_advertise_address: '{{ ansible_host }}'
kubernetes_control_plane_port: 6443
kubernetes_control_plane_pod_subnet: 10.128.0.0/9
kubernetes_control_plane_service_subnet: 10.96.0.0/12
kubernetes_control_plane_kubeconfig_user: maintainer
kubernetes_control_plane_manifest_directory: /etc/kubernetes/homelab

kubernetes_control_plane_lb_network_label: homelab/network
kubernetes_control_plane_lb_networks:
  - name: private
    start: 192.168.20.200
    stop: 192.168.20.220
    interface: eth1
  - name: public
    start: 192.168.30.200
    stop: 192.168.30.220
    interface: eth0

kubernetes_control_plane_cilium_version: 1.20.2
kubernetes_control_plane_cilium_values:
  ipam:
    mode: kubernetes
  kubeProxyReplacement: true
  k8sServiceHost: '{{ kubernetes_control_plane_advertise_address }}'
  k8sServicePort: '{{ kubernetes_control_plane_port }}'
  devices: "{{ kubernetes_control_plane_lb_networks | map(attribute='interface') | list }}"
  l2announcements:
    enabled: true
  k8sClientRateLimit:
    qps: 20
    burst: 40

kubernetes_control_plane_argocd_chart: oci://ghcr.io/argoproj/argo-helm/argo-cd
kubernetes_control_plane_argocd_chart_version: 10.9.2
kubernetes_control_plane_argocd_network: private
kubernetes_control_plane_argocd_ip: 192.168.20.200
kubernetes_control_plane_argocd_values:
  server:
    service:
      type: LoadBalancer
      labels: "{{ {kubernetes_control_plane_lb_network_label: kubernetes_control_plane_argocd_network} }}"
      annotations:
        lbipam.cilium.io/ips: '{{ kubernetes_control_plane_argocd_ip }}'
