---
- name: 踏み台ホストを構成する
  hosts: bastion
  serial: 1
  roles:
    - role: pacman-mirror
      tags: pacman_mirror
    - role: initialize-node
      tags: initialize_node
    - role: upgrade-packages
      tags: upgrade_packages
    - role: ssh
      tags: ssh
    - role: tailscale
      tags: tailscale
