---
- name: パッケージキャッシュを構成する
  hosts: cache
  serial: 1
  roles:
    - role: initialize-node
      tags: initialize_node
    - role: upgrade-packages
      tags: upgrade_packages
    - role: flexo
      tags: flexo
