---
- name: デプロイホストを構成する
  hosts: deployer
  serial: 1
  roles:
    - role: pacman-mirror
      tags: pacman_mirror
    - role: initialize-node
      tags: initialize_node
    - role: upgrade-packages
      tags: upgrade_packages
    - role: deployer
      tags: deployer
