---
- name: DNSサービスを構成する
  hosts: dns
  serial: 1
  roles:
    - role: pacman-mirror
      tags: pacman_mirror
    - role: initialize-node
      tags: initialize_node
    - role: upgrade-packages
      tags: upgrade_packages
    - role: pi-hole
      tags: pi_hole
