---
- name: Jenkinsサービスを構成する
  hosts: jenkins
  serial: 1
  roles:
    - role: initialize-node
      tags: initialize_node
    - role: upgrade-packages
      tags: upgrade_packages
    - role: jenkins
      tags: jenkins
