---
- name: Kubernetesホストを構成する
  hosts: kubernetes
  serial: 1
  roles:
    - role: pacman-mirror
      tags: pacman_mirror
    - role: upgrade-packages
      tags: upgrade_packages
    - role: initialize-node
      tags: initialize_node
    - role: sshd
      tags: sshd
