---
- name: LLMホストを初期化する
  hosts: llm
  serial: 1
  roles:
    - role: initialize-node
      tags: initialize_node
    - role: upgrade-packages
      tags: upgrade_packages

- name: LLMバックエンドを構成する
  hosts: llm_backend
  roles:
    - role: add-worker
      tags: add_worker
    - role: llm-backend
      tags: llm_backend

- name: LLM Web UIを構成する
  hosts: webui
  roles:
    - role: docker-host
      tags: docker_host
    - role: llm-webui
      tags: llm_webui

- name: LLMプロキシを構成する
  hosts: llm_proxy
  roles:
    - role: llm-proxy
      tags: llm_proxy
