---
- name: LLMホストを初期化する
  hosts: llm
  serial: 1
  roles:
    - role: pacman-mirror
      tags: pacman_mirror
    - role: initialize-node
      tags: initialize_node
    - role: upgrade-packages
      tags: upgrade_packages

- name: LLMバックエンドを構成する
  hosts: llm_backend
  roles:
    - role: add-worker
      tags: add_worker
    - role: llm-backend
      tags: llm_backend
