---
- name: Memoryサービスを構成する
  hosts: memory
  serial: 1
  roles:
    - role: pacman-mirror
      tags: pacman_mirror
    - role: initialize-node
      tags: initialize_node
    - role: upgrade-packages
      tags: upgrade_packages
    - role: docker-host
      tags: docker_host
    - role: hindsight
      tags: hindsight
