---
- name: Memoryサービスを構成する
  hosts: memory
  serial: 1
  roles:
    - role: initialize-node
      tags: initialize_node
    - role: upgrade-packages
      tags: upgrade_packages
    - role: hindsight
      tags: hindsight
