---
- name: Workerホストを構成する
  hosts: worker
  serial: 1
  roles:
    - role: initialize-node
      tags: initialize_node
    - role: upgrade-packages
      tags: upgrade_packages
    - role: add-worker
      tags: add_worker
