---
- name: 'pi-holeの稼動に必要なパッケージをインストール'
  become: true
  community.general.pacman:
    name: '{{ pi_hole_package_manifest.repository }}'
    state: present

- name: 'pi-holeをインストール'
  kewlfft.aur.aur:
    name: '{{ pi_hole_package_manifest.aur }}'
    state: present
  notify: 'pihole-FTLを再起動する'

- name: 'pihole-FTL.serviceを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: pihole-FTL

- name: 'resolvdの追加設定用ディレクトリを掘る'
  become: true
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: "directory"
    mode: '0755'

- name: 'resolvedの設定を置く'
  become: true
  ansible.builtin.copy:
    src: pi-hole.conf
    dest: /etc/systemd/resolved.conf.d/pi-hole.conf
    mode: '0644'
  notify:
    - 'systemd-resolvedを再起動する'
    - 'pihole-FTLを再起動する'

- name: 'adlistを更新'
  become: true
  ansible.builtin.command:
    cmd: 'pihole -g'
  changed_when: true
  tags: pi_hole_update
