---
- name: 'OpenChamberのuser managerを再起動する'
  become: true
  ansible.builtin.systemd_service:
    name: 'user@{{ openchamber_account.uid }}.service'
    state: restarted

- name: 'OpenChamberを再起動する'
  become: true
  become_user: '{{ openchamber_user }}'
  environment:
    XDG_RUNTIME_DIR: '/run/user/{{ ansible_facts["getent_passwd"][openchamber_user][1] }}'
    DBUS_SESSION_BUS_ADDRESS: 'unix:path=/run/user/{{ ansible_facts["getent_passwd"][openchamber_user][1] }}/bus'
  ansible.builtin.systemd_service:
    name: openchamber.service
    scope: user
    daemon_reload: true
    state: restarted
