apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "searxng.fullname" . }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "searxng.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "searxng.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: searxng
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SEARXNG_SETTINGS_PATH
              value: /etc/searxng-settings/settings.yml
            - name: FORCE_OWNERSHIP
              value: "false"
            - name: SEARXNG_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "searxng.secretName" . }}
                  key: {{ .Values.secretKey.existingSecretKey }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          volumeMounts:
            - name: settings
              mountPath: /etc/searxng-settings
              readOnly: true
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: settings
          configMap:
            name: {{ include "searxng.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
