---
pi_hole_package_manifest:
  repository:
    - php-cgi
    - openssl
    - patch
    - mbedtls
  aur:
    - openssl-1.1
    - pi-hole-web
    - pi-hole-ftl
    - pi-hole-core

pi_hole_dnsmasq_lines:
  - local=/local.k16em.net/
