---
initialize_node_package_manifest:
  repository:
    - archlinux-keyring
    - sudo
    - zsh
    - zsh-completions
    - vim
    - mosh
    - git
    - base-devel
    - rustup
    - pacman-contrib
    - python-pip
    - python-setuptools
    - prometheus-node-exporter
    - libfido2
  aur:
    - grafana-alloy-bin
