replicaCount: 1

image:
  repository: ghcr.io/searxng/searxng
  tag: ""
  pullPolicy: IfNotPresent

secretKey:
  existingSecret: ""
  existingSecretKey: secret-key
  value: ""

settings:
  use_default_settings: true
  general:
    instance_name: SearXNG
  search:
    formats:
      - html
      - json
  server:
    limiter: false
    image_proxy: false
    method: POST
  valkey:
    url: false

service:
  network: ""
  loadBalancerIP: ""
  hostname: ""
  ports:
    - name: http
      port: 80
  labels: {}
  annotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
