{{- if and (not .Values.secretKeyBase.existingSecret) .Values.secretKeyBase.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redmine.fullname" . }}
  labels:
    {{- include "redmine.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secretKeyBase.existingSecretKey }}: {{ .Values.secretKeyBase.value | b64enc | quote }}
{{- end }}
