---
- import_playbook: services/cache.yaml
- import_playbook: services/all.yaml
- import_playbook: services/bastion.yaml
- import_playbook: services/database.yaml
- import_playbook: services/dns.yaml
- import_playbook: services/llm.yaml
- import_playbook: services/openchamber.yaml
