image:
  repository: ghcr.io/open-webui/open-webui
  tag: ""
  pullPolicy: IfNotPresent

secretKey:
  existingSecret: ""
  existingSecretKey: secret-key
  value: ""

database:
  host: ""
  port: 5432
  name: ""
  user: ""
  existingSecret: ""
  existingSecretKey: password
  vectorDB: true

env: []

envFrom: []

persistence:
  existingClaim: ""
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

service:
  network: ""
  loadBalancerIP: ""
  hostname: ""
  ports:
    - name: http
      port: 80
  labels: {}
  annotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
