---
- name: '必要なパッケージを追加する'
  become: true
  community.general.pacman:
    name: '{{ item.name }}'
    state: installed
  with_items: '{{ required_packages }}'

- name: '必要なAURパッケージを追加する'
  kewlfft.aur.aur:
    name: '{{ item.name }}'
    state: present
  with_items: '{{ required_aur_packages }}'

- name: 'llmグループを作成する'
  become: true
  ansible.builtin.group:
    name: llm
    state: present

- name: 'モデル用ディレクトリを掘る'
  become: true
  ansible.builtin.file:
    path: '{{ llama_swap_models_dir }}'
    state: directory
    owner: root
    group: llm
    mode: '2750'

- name: 'llama-swapのサービスユニットファイルを上書きする用のディレクトリを作成する'
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/llama-swap.service.d/
    state: "directory"
    recurse: true
    mode: '0755'

- name: 'llama-swapの上書き用ユニットファイルを置く'
  become: true
  ansible.builtin.template:
    src: llama-swap.override.conf.j2
    dest: /etc/systemd/system/llama-swap.service.d/override.conf

- name: 'llama-swap.serviceを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: llama-swap

- name: 'llama-swapの設定用ディレクトリを掘る'
  become: true
  ansible.builtin.file:
    path: '{{ llama_swap_config_dir }}'
    state: directory
    owner: root
    mode: '0755'

- name: 'llama-swapの設定ファイルを置く'
  become: true
  ansible.builtin.template:
    src: llama-swap.config.yaml.j2
    dest: '{{ llama_swap_config_dir }}/config.yaml'
    mode: '0644'
    validate: '/usr/bin/python -c "import yaml, sys; yaml.safe_load(open(sys.argv[1]))" %s'

