---
hermes_package_manifest:
  repository:
    - ripgrep
    - ffmpeg
    - nss
    - at-spi2-core
    - cups
    - libdrm
    - libxkbcommon
    - mesa
    - pango
    - cairo
    - alsa-lib
  aur:
    - python311

hermes_ssh_hosts: '{{ groups["all"] | difference(groups.get("proxmox", [])) | difference([inventory_hostname]) | sort }}'
