---
hermes_package_manifest:
  repository:
    - ripgrep
    - ffmpeg
    - nss
    - at-spi2-core
    - cups
    - libdrm
    - libxkbcommon
    - mesa
    - pango
    - cairo
    - alsa-lib
  aur:
    - python311
