---
- name: "archlinux-keyringを先に更新かける"
  become: true
  community.general.pacman:
    name: '{{ upgrade_packages_package_manifest.repository | select("equalto", "archlinux-keyring") | first }}'
    state: latest
    update_cache: true

- name: "pacman -Syyuする"
  become: true
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  register: result

- name: "更新されたパッケージがあるなら、再起動"
  become: true
  ansible.builtin.reboot:
    msg: "Ansibleでパッケージ更新があったので、再起動します"
  when:
    - result.changed
    - "not 'jenkins' in group_names"

- name: "pacman-contribを入れる"
  become: true
  community.general.pacman:
    name: '{{ upgrade_packages_package_manifest.repository | select("equalto", "pacman-contrib") | first }}'
    state: latest

- name: "pacmanのキャッシュを消す"
  become: true
  ansible.builtin.command:
    cmd: paccache --remove --keep 3
  register: paccache
  changed_when: paccache.stdout | length > 0
  when: "'cache' not in group_names"
